# Generated by Django 4.1 on 2022-08-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="summary", field=models.TextField(blank=True),
        ),
    ]
