# Generated by Django 4.1 on 2022-08-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="features",
            field=models.BooleanField(default=False),
        ),
    ]
