# Generated by Django 4.1 on 2022-08-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=120)),
                ("item_description", models.TextField(max_length=120)),
                (
                    "item_price",
                    models.DecimalField(decimal_places=2, max_digits=100000),
                ),
            ],
        ),
    ]
